import {
  siteSettings,
  seoSettings,
  navbar,
  heroSection,
  countdownSettings,
  aboutEvent,
  eventDescription,
  eventHighlights,
  ticketSettings,
  offlineTicketSellers,
  guestStars,
  sponsors,
  partners,
  gallery,
  faq,
  socialLinks,
  contactInfo,
  footerSettings,
  sectionSettings,
} from './schema';

export const schemaTypes = [
  siteSettings,
  seoSettings,
  navbar,
  heroSection,
  countdownSettings,
  aboutEvent,
  eventDescription,
  eventHighlights,
  ticketSettings,
  offlineTicketSellers,
  guestStars,
  sponsors,
  partners,
  gallery,
  faq,
  socialLinks,
  contactInfo,
  footerSettings,
  sectionSettings,
];
